spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
    default-property-inclusion: non_null

  application:
    name: solr
    data:
      solr:
        host: http://localhost:8983/solr/moclle